### ISSUE TITLE
Relationships not returned

### ISSUE THREAD

**Issue by michaelrkn** [locks/ember-localstorage-adapter#68]
I'm working on an example blogging app (https://github.com/michaelrkn/blogger/tree/86b134b05d9749136b76202841769c2c6808ec99) for an Ember class I'm teaching. I'm using the LS adapter.

In my models, a post has many comments. As instructed in the LS adapter README, I have not used `{async: true}` (at least at the point at which the linked commit was made).

I can create a post, and write some comments on it. However, if I refresh the page, and then click on a post, I get the error "You looked up the 'comments' relationship on '<Blogger.Post:ember477:00hdt>' but some of the associated records were not loaded." If I load the page at the URL for that particular post (eg file:///Users/michael/Code/blogger/index.html#/00hdt), that particular route won't throw an error, but browsing to any other post will.

If I add `{async: true}`, the app does not throw those errors.

**Comment by mylen** [comment]
any update on this ?

**Comment by masciugo** [comment]
the `afterModel` hook workaround to pre-load all comments worked form me. But I think this bug persists

**Comment by kurko** [comment]
This is annoying, for sure. Anyone volunteer for a fix/PR? I am not really working in any app with LS right now, so I lack the time for that.

**Comment by Kilowhisky** [comment]
I don't know enough about ember data to create a fix but i think i've found the location of the problem. 

https://github.com/kurko/ember-localstorage-adapter/blob/master/localstorage_adapter.js#L408

It has to do with Ember-CLI and requiring an adapter for every model. 

`if (relationEmbeddedId && foreignAdapter === adapter)` 

The foreign adapter is not the same as the current adapter because they are different objects. But their types are the same which should be enough, right?  I couldn't find anything to compare types besides looking at the model namespace and comparing it though.

**Comment by oleander** [comment]
Any news on this one? This is still a problem in Ember Data 2.x

**Comment by fsmanuel** [comment]
@oleander because of that and other problems i build an [adapter](https://github.com/funkensturm/ember-local-storage#adapter--serializer) for ember data versions that include the JSONAPIAdapter/Serializer. The default behavior of relationships in ember data 2.x is async that solve the problem.

**Comment by locks** [comment]
#124 says that it fixes this issue, please reopen if that's not the case.
